---
- hosts: all
  gather_facts: false
  become: true

  roles:
    - create_network
    - install_docker
    - launch_app
    - launch_database
    - launch_proxy

  vars:
    ansible_python_interpreter: /usr/bin/python3
