---
# tasks file for roles/launch_proxy
- name: Run API
  docker_container:
    name: api
    image: marionddlr/tp1-backend:1.0
    state: started
    networks:
      - name: app-network
    env:
      DB_host: database
      DATABASE_USER: usr
      DATABASE_PASSWORD: pwd
      DATABASE_NAME: db
      DATABASE_PORT: "5432"
  vars:
    ansible_python_interpreter: /usr/bin/python3