name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI devops 2024"]
    types:
      - completed
    branches: 
      - main

jobs:
  run-main-playbook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3  # Use the webfactory/ssh-agent action to set up SSH
      with:
        ssh-private-key: ${{ secrets.ANSIBLE_TOKEN }}  # Set the SSH private key from GitHub repository secrets
    - name: Set up Ansible
      run: |
        sudo apt update
        sudo apt install ansible -y

    - name: Run main playbook
      run: |
        ansible-playbook -i inventories/setup.yml my-project/ansible/playbook.yml
      continue-on-error: false  # Ensure this step fails the job if it fails
