name: CI DevOps 2024

on:
  push:
    branches:
      - develop
      - main
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: |
          cd Backend/simple-api-student-main
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=devops-marionddlr_project \
            -Dsonar.organization=devops-marionddlr \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./pom.xml

  build-and-push-docker-image:
    needs: test-backend
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}

      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./Backend/simple-api-student-main
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest

      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./Postgres
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest

      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./HTTP
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest

