name: Test Backend

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build and test with Maven
        run: |
          cd Backend/simple-api-student-main
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=devops-marionddlr_project \
            -Dsonar.organization=devops-marionddlr \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./pom.xml
